"""
Spider Xray manager — automatic VLESS Reality + XHTTP configuration generator.

The user edits ONE file only: config.json (repo root):

    {
      "tcp_proxy_domain": "hayabusa.proxy.rlwy.net",  # public TCP proxy domain
      "external_port": 22124,                          # public port users connect to
      "internal_port": 443,                            # port Xray listens on inside container
      "sni": "is1-ssl.mzstatic.com"                    # Reality SNI / dest
    }

Rules:
  - Xray ALWAYS listens on internal_port. external_port is NEVER a listen port.
  - Subscription links ALWAYS use tcp_proxy_domain:external_port.
  - Reality keys + shortId are generated by Xray itself (never fake) and persisted.
  - User settings in config.json are never overwritten; only UUID / keys / shortId
    are (re)generated.

This module drives its own dedicated Xray-core process for the Reality inbound and
does NOT touch Marzban's own core, database, dashboard, users, or authentication.
User UUIDs are read from the same Marzban DB (Proxy.settings["id"] for vless).
"""

import json
import logging
import os
import re
import secrets
import shutil
import stat
import subprocess
import time
import urllib.request
import zipfile
from pathlib import Path
from typing import List, Optional
from urllib.parse import quote

logger = logging.getLogger("uvicorn.error")

# --- Paths (env-overridable, spec-mandated defaults) ------------------------
XRAY_CORE_DIR = Path(os.environ.get("SPIDER_XRAY_CORE_DIR", "/app/xray-core"))
XRAY_BINARY = Path(os.environ.get("XRAY_BINARY_PATH", str(XRAY_CORE_DIR / "xray")))
XRAY_CONFIG_DIR = Path(os.environ.get("SPIDER_XRAY_CONFIG_DIR", "/app/xray-config"))
XRAY_CONFIG_PATH = Path(os.environ.get("XRAY_CONFIG_PATH", str(XRAY_CONFIG_DIR / "config.json")))
XRAY_LOGS_DIR = Path(os.environ.get("SPIDER_XRAY_LOGS_DIR", "/app/xray-logs"))

# User-editable config (repo root) + persisted generated secrets.
USER_CONFIG_PATH = Path(os.environ.get("SPIDER_USER_CONFIG", "config.json")).resolve()
TEMPLATE_PATH = Path(
    os.environ.get("SPIDER_XRAY_TEMPLATE", "templates/xray_config_template.json")
).resolve()
KEYS_PATH = XRAY_CONFIG_DIR / "reality_keys.json"

XRAY_DOWNLOAD_URL = (
    "https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip"
)

INBOUND_TAG = "VLESS-REALITY-XHTTP"
XHTTP_PATH = "/"
XHTTP_MODE = "auto"
FINGERPRINT = "chrome"
REMARK = os.environ.get("SPIDER_REMARK", "Spider")

DEFAULT_USER_CONFIG = {
    "tcp_proxy_domain": "",
    "external_port": "0",
    "internal_port": "443",
    "sni_host": "is1-ssl.mzstatic.com",
    "network": "xhttp",
    "security": "reality",
    "type": "vless",
    "xray_binary": str(XRAY_BINARY),
}


# ===========================================================================
# Directory setup
# ===========================================================================
def ensure_dirs() -> None:
    for d in (XRAY_CORE_DIR, XRAY_CONFIG_DIR, XRAY_LOGS_DIR):
        try:
            d.mkdir(parents=True, exist_ok=True)
        except PermissionError as e:  # noqa: PERF203
            logger.warning(f"[Xray] could not create {d}: {e}")


# ===========================================================================
# 1. User config (single source of truth, never overwritten)
# ===========================================================================
def load_user_config() -> dict:
    """Load the user-editable config.json, applying defaults for missing keys.

    Never overwrites an existing file. Creates one from defaults only if absent.
    """
    if USER_CONFIG_PATH.exists():
        cfg = {**DEFAULT_USER_CONFIG, **json.loads(USER_CONFIG_PATH.read_text())}
    else:
        cfg = dict(DEFAULT_USER_CONFIG)
        USER_CONFIG_PATH.write_text(json.dumps(cfg, indent=2) + "\n")
        logger.warning(f"[Spider] created default {USER_CONFIG_PATH}; edit it and redeploy")

    if not cfg["tcp_proxy_domain"] or int(cfg["external_port"] or 0) <= 0:
        raise RuntimeError(
            "[Spider] config.json must set tcp_proxy_domain and external_port"
        )
    logger.info(f"[Spider] Domain: {cfg['tcp_proxy_domain']}  External port: {cfg['external_port']}")
    logger.info(f"[Xray] Internal listen port: {cfg['internal_port']}  SNI: {cfg['sni_host']}")

    # Honor an explicit xray_binary from config if it exists (else keep default).
    global XRAY_BINARY
    cfg_bin = cfg.get("xray_binary")
    if cfg_bin and Path(cfg_bin).exists():
        XRAY_BINARY = Path(cfg_bin)
        logger.info(f"[Xray] Using binary from config: {XRAY_BINARY}")
    return cfg


# ===========================================================================
# 2. Xray Core detection / installation
# ===========================================================================
def _run_version(binary: Path) -> Optional[str]:
    try:
        out = subprocess.check_output(
            [str(binary), "version"], stderr=subprocess.STDOUT, timeout=30
        ).decode("utf-8", "replace")
        return out.strip().splitlines()[0] if out.strip() else ""
    except Exception as e:  # noqa: BLE001
        logger.warning(f"[Xray] version check failed: {e}")
        return None


def install_xray(force: bool = False) -> Path:
    """Download + install official Xray-core. Raises RuntimeError on failure."""
    if XRAY_BINARY.exists() and not force:
        return XRAY_BINARY

    XRAY_CORE_DIR.mkdir(parents=True, exist_ok=True)
    zip_path = XRAY_CORE_DIR / "xray.zip"
    logger.info(f"[Xray] Downloading Xray-core from {XRAY_DOWNLOAD_URL}")
    try:
        with urllib.request.urlopen(XRAY_DOWNLOAD_URL, timeout=120) as resp, open(zip_path, "wb") as fh:
            shutil.copyfileobj(resp, fh)
        with zipfile.ZipFile(zip_path) as zf:
            zf.extractall(XRAY_CORE_DIR)
    except Exception as e:  # noqa: BLE001
        raise RuntimeError(f"[Xray] install failed: {e}") from e
    finally:
        zip_path.unlink(missing_ok=True)

    if not XRAY_BINARY.exists():
        raise RuntimeError(f"[Xray] binary not found at {XRAY_BINARY} after extraction")
    st = os.stat(XRAY_BINARY)
    os.chmod(XRAY_BINARY, st.st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)

    version = _run_version(XRAY_BINARY)
    if not version:
        raise RuntimeError("[Xray] installed binary failed `xray version`")
    logger.info(f"[Xray] Installed successfully: {version}")
    return XRAY_BINARY


def ensure_xray() -> Path:
    """Ensure a runnable Xray binary exists; install if missing. Fail-fast."""
    if XRAY_BINARY.exists():
        version = _run_version(XRAY_BINARY)
        if version:
            logger.info(f"[Xray] Binary found: {XRAY_BINARY}")
            logger.info(f"[Xray] Version: {version}")
            return XRAY_BINARY
        logger.warning("[Xray] existing binary not runnable; reinstalling")
        return install_xray(force=True)
    logger.info("[Xray] Binary missing; installing...")
    return install_xray()


# ===========================================================================
# 3. Reality keys (generated by Xray, persisted, never fake)
# ===========================================================================
def generate_x25519() -> dict:
    """Run `xray x25519` and parse the real keypair."""
    out = subprocess.check_output(
        [str(XRAY_BINARY), "x25519"], stderr=subprocess.STDOUT, timeout=30
    ).decode("utf-8", "replace")
    # Handles both legacy ("Private key: X / Public key: Y") and newer
    # ("PrivateKey: X / Password (PublicKey): Y") Xray output formats.
    priv = re.search(r"[Pp]rivate[ _]?[Kk]ey:\s*(\S+)", out)
    pub = re.search(r"(?:[Pp]ublic[ _]?[Kk]ey|Password \(PublicKey\)):\s*(\S+)", out)
    if not priv or not pub:
        raise RuntimeError(f"[Xray] could not parse x25519 output:\n{out}")
    return {"privateKey": priv.group(1), "publicKey": pub.group(1)}


def load_or_create_keys() -> dict:
    """Return persisted Reality keys + shortId, generating any that are missing."""
    keys = {}
    if KEYS_PATH.exists():
        try:
            keys = json.loads(KEYS_PATH.read_text())
        except (OSError, json.JSONDecodeError):
            keys = {}

    changed = False
    if not keys.get("privateKey") or not keys.get("publicKey"):
        keys.update(generate_x25519())
        changed = True
        logger.info("[Xray] Reality keypair generated")
    if not keys.get("shortId"):
        keys["shortId"] = secrets.token_hex(8)  # 16 hex chars
        changed = True
        logger.info("[Xray] shortId generated")

    if changed:
        KEYS_PATH.parent.mkdir(parents=True, exist_ok=True)
        KEYS_PATH.write_text(json.dumps(keys, indent=2) + "\n")
        logger.info(f"[Xray] Reality secrets persisted: {KEYS_PATH}")
    return keys


# ===========================================================================
# 4. Config generation
# ===========================================================================
def _collect_vless_clients() -> List[dict]:
    """Read active users' VLESS UUIDs from Marzban's DB. Never raises."""
    clients: List[dict] = []
    try:
        from app.db import GetDB, crud
        from app.models.proxy import ProxyTypes
        from app.models.user import UserStatus

        with GetDB() as db:
            users = crud.get_users(db, status=UserStatus.active)
            if isinstance(users, tuple):
                users = users[0]
            for u in users:
                for proxy in u.proxies:
                    if proxy.type != ProxyTypes.VLESS:
                        continue
                    uuid = (proxy.settings or {}).get("id")
                    if uuid:
                        clients.append({"id": str(uuid), "email": u.username})
    except Exception as e:  # noqa: BLE001
        logger.warning(f"[Xray] could not collect VLESS clients from DB: {e}")
    return clients


def render_template(user_cfg: dict, keys: dict) -> dict:
    """Render templates/xray_config_template.json by substituting placeholders.

    Placeholders: {{INTERNAL_PORT}} {{CLIENTS}} {{SNI_HOST}} {{PRIVATE_KEY}} {{SHORT_ID}}.
    CLIENTS is rendered as the inner JSON of the clients array (comma-joined
    objects), so the template's surrounding [ ] stays intact.
    Xray ALWAYS listens on internal_port; external_port never appears here.
    """
    if not TEMPLATE_PATH.exists():
        raise RuntimeError(f"[Xray] template not found: {TEMPLATE_PATH}")
    raw = TEMPLATE_PATH.read_text()

    clients = _collect_vless_clients()
    clients_json = ",\n          ".join(
        json.dumps({"id": c["id"], "email": c["email"]}) for c in clients
    )

    rendered = (
        raw.replace("{{INTERNAL_PORT}}", str(int(user_cfg["internal_port"])))
        .replace("{{CLIENTS}}", clients_json)
        .replace("{{SNI_HOST}}", user_cfg["sni_host"])
        .replace("{{PRIVATE_KEY}}", keys["privateKey"])
        .replace("{{SHORT_ID}}", keys["shortId"])
    )
    try:
        return json.loads(rendered)
    except json.JSONDecodeError as e:
        raise RuntimeError(f"[Xray] rendered template is invalid JSON: {e}\n{rendered}") from e


def generate_config(user_cfg: dict, keys: dict) -> Path:
    XRAY_CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    cfg = render_template(user_cfg, keys)
    XRAY_CONFIG_PATH.write_text(json.dumps(cfg, indent=2) + "\n")
    n = len(cfg["inbounds"][0]["settings"]["clients"])
    logger.info(f"[Xray] Config generated: {XRAY_CONFIG_PATH} ({n} clients)")
    return XRAY_CONFIG_PATH


# ===========================================================================
# 5. Validation
# ===========================================================================
def validate_config() -> None:
    """Run `xray run -test -config ...`. Raise RuntimeError with exact error."""
    try:
        out = subprocess.run(
            [str(XRAY_BINARY), "run", "-test", "-config", str(XRAY_CONFIG_PATH)],
            capture_output=True, text=True, timeout=60,
        )
    except Exception as e:  # noqa: BLE001
        raise RuntimeError(f"[Xray] validation could not run: {e}") from e

    combined = (out.stdout or "") + (out.stderr or "")
    if out.returncode != 0 or "Configuration OK" not in combined:
        raise RuntimeError(
            f"[Xray] Config validation FAILED (exit {out.returncode}):\n{combined.strip()}"
        )
    logger.info("[Xray] Config validation OK")


# ===========================================================================
# 6. VLESS Reality + XHTTP subscription link generation
# ===========================================================================
def build_vless_link(uuid: str, user_cfg: dict, keys: dict) -> str:
    """Build a VLESS Reality+XHTTP link using the EXTERNAL Railway endpoint.

    Rejects any attempt to produce a legacy WS/TLS link.
    """
    domain = user_cfg["tcp_proxy_domain"]
    port = int(user_cfg["external_port"])
    sni = user_cfg["sni_host"]
    query = (
        f"encryption=none&security=reality&sni={sni}&fp={FINGERPRINT}"
        f"&pbk={keys['publicKey']}&sid={keys['shortId']}"
        f"&type=xhttp&path={quote(XHTTP_PATH, safe='')}&mode={XHTTP_MODE}"
    )
    link = f"vless://{uuid}@{domain}:{port}?{query}#{quote(REMARK)}"
    _assert_valid_link(link, port)
    return link


def _assert_valid_link(link: str, external_port: int) -> None:
    """Reject invalid (legacy WS/TLS) subscription links."""
    for banned in ("security=tls", "type=ws", "&host="):
        if banned in link:
            raise RuntimeError(f"[Spider] refusing to emit legacy link fragment {banned!r}")
    if "security=reality" not in link or "type=xhttp" not in link:
        raise RuntimeError("[Spider] link is not Reality+XHTTP")


def build_user_links(user_cfg: dict, keys: dict) -> List[str]:
    return [build_vless_link(c["id"], user_cfg, keys) for c in _collect_vless_clients()]


# ===========================================================================
# Orchestration
# ===========================================================================
class SpiderXray:
    def __init__(self) -> None:
        self.process: Optional[subprocess.Popen] = None
        self.user_cfg: Optional[dict] = None
        self.keys: Optional[dict] = None

    @property
    def ready(self) -> bool:
        return bool(self.user_cfg and self.keys)

    def start(self) -> None:
        """Startup flow (spec section 10):
        check xray -> load config -> keys -> generate -> validate -> start xray.
        """
        ensure_dirs()
        ensure_xray()                      # 1
        self.user_cfg = load_user_config()  # 2
        self.keys = load_or_create_keys()   # 3
        generate_config(self.user_cfg, self.keys)  # 4
        validate_config()                   # 5

        self.process = subprocess.Popen(    # 6
            [str(XRAY_BINARY), "run", "-config", str(XRAY_CONFIG_PATH)],
            env={**os.environ},
        )
        time.sleep(1)
        if self.process.poll() is not None:
            raise RuntimeError(
                f"[Xray] process exited immediately (code {self.process.returncode})"
            )
        logger.info("[Xray] Started successfully")

    def stop(self) -> None:
        if self.process and self.process.poll() is None:
            self.process.terminate()
            try:
                self.process.wait(timeout=10)
            except subprocess.TimeoutExpired:
                self.process.kill()
        self.process = None


spider = SpiderXray()
